### ISSUE TITLE
Change Model Results Discrepancy

### ISSUE THREAD

**Issue by ijyliu** [current12/Stat-222-Project#100]
@OwenLin2001 @current12 

The change model results on GitHub do not match those presented.

https://github.com/current12/Stat-222-Project/blob/main/Output/Modelling/XGBoost/Tables/change_smote_model_comparison_df.tex

for example, versus

![image](https://github.com/current12/Stat-222-Project/assets/67396209/07ca4dd4-93b8-483e-a40f-f8ae8f72649b)

Please ensure GitHub is up to date.

Thanks!

**Comment by OwenLin2001** [comment]
prediction files are also updated. just need to update .tex file and we can close the issue.

**Comment by ijyliu** [comment]
I saw some discrepancies for logistic regression too. Can you check those?

Also, for the tex files, just run all the notebooks in the figures and
tables folder of logistic regression and xgboost
