### ISSUE TITLE
Initial Literature Exploration

### ISSUE THREAD

**Issue by ijyliu** [current12/Stat-222-Project#12]
Review data, NLP sections of

https://pubsonline.informs.org/doi/epdf/10.1287/ijds.2022.00018

Look at how credit risk prediction is defined, what rating agencies are used.

Feel free to search the web/literature more broadly on credit rating prediction, using earnings calls for NLP, etc.

**Comment by seanzhou1207** [comment]
How is the credit risk prediction task defined? How can we match up the timeframe of earning calls/credit ratings?

**Comment by seanzhou1207** [comment]
**How is the credit risk prediction task defined? **
default v.s. no default [source](https://www.sciencedirect.com/science/article/pii/S1062976907000762)
credit rating classification [source](https://ieeexplore.ieee.org/document/9344973)

**How can we match up the timeframe of earning calls/credit ratings?**
Annual (end of the year) for each company [source](https://ieeexplore.ieee.org/document/9344973)
Year prior to bankruptcy [source] (https://www.sciencedirect.com/science/article/pii/S0957417417302415?casa_token=3FpVYt7l5eUAAAAA:lHU9MtYQUB4K40zPbfXPJvAp8k0HfvKlxlMATmRuqtZvCz7Ih3TU2yMVE_ycMLkjC1WIpCjc)
