### ISSUE TITLE
Progress Slide for 2/23

### ISSUE THREAD

**Issue by ijyliu** [current12/Stat-222-Project#14]
@seanzhou1207 

I'd suggest you be in charge of these each week

By 2/23, ideally we will have all the data loaded

**Comment by seanzhou1207** [comment]
https://docs.google.com/presentation/d/1JJEnThJ8J-kww_SiqMceNVPTG_3i5U472d_8RIgSb-o/edit#slide=id.g2bb068cfd12_0_0

**Comment by ijyliu** [comment]
Make sure he sees this stuff

Could be in a reply to the email or in the slide

https://github.com/current12/Stat-222-Project/issues/15#issue-2143398149

**Comment by ijyliu** [comment]
Especially need to know what sectors to use. Bc each dataset has different ones

**Comment by ijyliu** [comment]
Also should get his take on this

https://github.com/current12/Stat-222-Project/issues/21#issue-2149935539
