### ISSUE TITLE
Prediction Setup

### ISSUE THREAD

**Issue by ijyliu** [current12/Stat-222-Project#21]
I'm kind of unsure about the feasibility of predicting credit ratings on each earnings call date, because I expect that rating agencies would need some time to absorb information from the earnings call + released financial statements and update their rating. We would probably need to focus on lead variables and predict something like rating at the next earnings call + financial statement release date.

Another option that's perhaps cleaner is just picking dates on a fixed schedule for every quarter and company - 1/1, 4/1, 8/1, etc. in every year - and predicting the current credit rating on those fixed dates for every company using the most recent financial statement and earnings call before them.

What do you guys think about these? We can also ask Libor and get his input on the feasibility of these prediction setups and how long he thinks rating changes might be lagged from financial releases and calls.

**Comment by current12** [comment]
I think the first one is more practical, we can just pick a fixed number of earning calls and financial statements before each credit rating is announced(predict the credit rating before the next earning call is released)

**Comment by ijyliu** [comment]
Ok, I'd say we should probably stick to one as it would be very computationally intensive to use multiple earnings calls to predict one rating.

This should be simple enough with the way I'm setting things up currently. For each earnings call, predict the credit rating on the next earnings call date.

**Comment by seanzhou1207** [comment]
So for each new credit score, find the most recent earning call date (as long as it's before a pre-specified threshold) and use the earning call and metrics related to it. I think this makes sense as generally there is a time-lag associated with credit change anyways. 

if we do it this way, just need to make sure 1 specific earning call + financial metric is not used for multiple credit ratings.

**Comment by ijyliu** [comment]
Think we discussed this earlier but that's something different because then we would be conditioning on there being a change in credit rating. It's predicting the new credit rating conditional on there being a change in rating. 

We could do it, it's just something different

**Comment by seanzhou1207** [comment]
I'm still confused on your definition for "change" in rating, are you defining a change as when a new rating came out? Because ofc the new rating might just be the same as before. I just think about the ratings as the available ratings we have rather than signaling a change.

**Comment by ijyliu** [comment]
You're right, this is actually predicting the rating whenever there is an issuance of a rating. Makes more sense to model that. But I don't know anything about how decisions to issue ratings are made and if they are meaningful. They certainly don't seem to be at regular intervals.

**Comment by ijyliu** [comment]
I think libor said (need to check though) the ratings are issued - changed or reaffirmed - when companies make new debt offerings. That seems kind of endogenous to me

**Comment by ijyliu** [comment]
Here's what the chatbot says, seems pretty ad hoc to me:

Corporate credit ratings are typically issued by credit rating agencies when a corporation seeks to issue debt securities or anytime there is a significant change in the company's financial situation or debt levels. These ratings can also be updated periodically to reflect changes in the financial health or business circumstances of the corporation.

The process begins when a corporation engages a credit rating agency (or agencies) to rate a specific debt issue or the company's general creditworthiness. This is often done ahead of issuing new bonds or debt instruments, but can also be initiated by the agency itself as part of its regular surveillance of issuers within its purview.

After the initial rating is issued, the agency monitors the corporation's financial health and performance, as well as any relevant economic and market developments. Ratings can be revised upwards or downwards if the agency perceives changes in the risk of default. These updates can occur at any time, depending on the circumstances prompting a reevaluation of the rating.

**Comment by ijyliu** [comment]
Discussion with Libor today: 

Predict direction of movement in credit rating (upgrade, flat, downgrade) at fixed quarter dates using the most recent earnings call and financial statements. Add a control or interaction for the number of days since the earnings call or statement release date.

**Comment by ijyliu** [comment]
Using fixed quarter dates, but unsure if doing credit rating values (grade or investment-grade v. not) or change directions (code/data is setup to easily do either)

Looking to add number of days since earnings call or statement release if earnings call variable is of good quality
