### ISSUE TITLE
Backfill Credit Ratings All The Way To Q1 2010?

### ISSUE THREAD

**Issue by ijyliu** [current12/Stat-222-Project#30]
Libor mentioned potentially backfilling credit ratings to 2010/the start of the data for all companies. We'd create a synthetic rating which is the earliest rating for which we currently have data, and assign it a date of 1/1/2010 (or actually 4/6/2010-ish since that's when our data actually starts).

This would fix a quirk of the sample we seem to have - companies enter in a very staggered fashion, and the number of companies we have is increasing over time.

![image](https://github.com/current12/Stat-222-Project/assets/67396209/40f3501c-eab9-40b7-8b42-1a7c3e51896a)

(from credit ratings eda)

But I'm not sure if this is a good approach. It really seems to be stretching assumptions about the credit rating data. It'd be believing that a ton of companies just didn't get rating issuances at all in 2010, etc - when I think the more plausible explanation is that our data is just incomplete/not very good for those years. My perception of the data's incompleteness is informed by its sources - a lot of webscraping that might have only started in later years. Backfilling would also be wrong for companies that actually only started existing/only started issuing bonds after 2010.

What do you think about backfilling? I'm inclined to not do it.

**Comment by ijyliu** [comment]
I also think that when he said this he was maybe still under the impression our raw data was changes in ratings rather than what we actually have, which is both changes in ratings and reaffirmations (issuances).

We just don't have data for 2010 and early years for most companies. If we had change data, then maybe you could interpret that as no change, but since we have both changes and reaffirmations at the times we do have, that's a hard case to make.

**Comment by seanzhou1207** [comment]
Yeah I think just the multi-class classification makes sense to me too. We don’t necessarily need to follow his advice.

**Comment by OwenLin2001** [comment]
Need some more details on how we craft new columns (change in credit rating). And in the case of classifying rating, how to impute the credit rating.

**Comment by ijyliu** [comment]
Check out the new code I put in #26

**Comment by ijyliu** [comment]
decided not to backfill
