### ISSUE TITLE
Earnings Call Web Scraping

### ISSUE THREAD

**Issue by ijyliu** [current12/Stat-222-Project#33]
Do 10 of each and then multiply for estimate.

Time estimate for scraping earnings call date, year and quarter it's for for all current credit ratings and earnings calls companies, years, quarters.

Time estimate for scraping transcript, earnings call date, year, and quarter for all credit rating companies.

If not more than a few hours, implement.

**Comment by ijyliu** [comment]
@current12 suggest saving as parquet files!

**Comment by current12** [comment]
Done
