### ISSUE TITLE
Integrate Annotation Project Question Category Classifications

### ISSUE THREAD

**Issue by ijyliu** [current12/Stat-222-Project#60]
Consider integrating labels/data from annotation project as features.

**Comment by ijyliu** [comment]
@current12 @seanzhou1207 @OwenLin2001 do you guys have writeup on this to share so we can assess if it's useful? thanks

**Comment by OwenLin2001** [comment]
[guidelines (1).pdf](https://github.com/current12/Stat-222-Project/files/15170841/guidelines.1.pdf)
We have a guideline from AP. Don't think it will be useful given the complexity of "cognitive level" of a question. 
The inter-annotator agreement is around 0.5 which is not as confident as we hope. 
This is also on the individual question level so I think we can just dismiss this issue.

**Comment by ijyliu** [comment]
possible but dont have time
