### ISSUE TITLE
Sampled version of firm network graph

### ISSUE THREAD

**Issue by ijyliu** [current12/Stat-222-Project#95]
experiment with making graph less cluttered

**Comment by ijyliu** [comment]
@seanzhou1207 download or pull this file and open it in your browser locally:

https://github.com/current12/Stat-222-Project/blob/main/Output/Company%20Mentions%20Network/Firm_Company_Mentions_Network_50_Percent_Node_Sample.html

do you think this is better for the firm network? I cut the number of nodes in half. you still kind of see sectoral connections in a few places.

other things to possibly explore: color coding the nodes/firms by sector. we could do this on the original data or on this reduced sample

**Comment by seanzhou1207** [comment]
Yes looks great already.

**Comment by ijyliu** [comment]
updated link in google slides

**Comment by ijyliu** [comment]
libor suggested coloring by sector (independently of me!) so probably going to do that!
